name       : dejagnu
version    : 1.6.2
release    : 2
source     :
    - https://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.2.tar.gz : 0d0671e1b45189c5fc8ade4b3b01635fb9eeab45cf54f57db23e4c4c1a17d261
license    : GPL-3.0-or-later
component  : programming.tools
summary    : DejaGnu is a framework for testing other programs
description: |
    DejaGnu is a framework for testing other programs. Its purpose is to provide a single front end for all tests. Think of it as a custom library of Tcl procedures crafted to support writing a test harness. A test harness is the testing infrastructure that is created to support a specific program or tool. Each program can have multiple testsuites, all supported by a single test harness.
builddeps  :
    - expect-devel
rundeps    :
    - expect
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
